name: Go

on:
  push:
    branches: [main, develop, "feature/*"]
  pull_request:
    branches: [main, develop, "feature/*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        # run: go test -gcflags=-l -v  -coverprofile=coverage.txt -covermode=atomic ./...
        run: go test ./... -coverprofile=test.out -covermode=count -json > report.json

      - name: Run Gosec Security Scanner
        run: |
          go get github.com/securego/gosec/cmd/gosec
          gosec -no-fail -fmt=sonarqube -out secreport.json ./...

      #- name: Codecov
      #  uses: codecov/codecov-action@v2.1.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          # args: --out-format checkstyle > golangci-lint.out
          only-new-issues: true

      - name: Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
